### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by adhityanadooli** [styler00dollar/VSGAN-tensorrt-docker#30]
When I try to render it gives me this error: (first picture is what my config looks like)
![image](https://user-images.githubusercontent.com/127269031/225179256-c4f0e0b8-1538-4c8f-b3b1-a905081dab27.png)

```
 Failed to parse script: Python exception: unexpected indent (inference_config.py, line 198)

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "inference.py", line 4, in <module>
    from inference_config import inference_clip
  File "/workspace/tensorrt/inference_config.py", line 198
    upscale_model_inference = ESRGAN_inference(model_path="/workspace/tensorrt/models/RealESRGAN_x4plus_anime_6B.pth", fp16=False, tta=False, tta_mode=1)
IndentationError: unexpected indent

inference.py: Generic error in an external library

**Comment by adhityanadooli** [comment]
Also is their a specific command I should be using to render this in CMD based of my config other than `ffmpeg -f vapoursynth -i inference.py example.mkv -y`?

**Comment by styler00dollar** [comment]
Indent is basic python syntax. Check your amount of spaces and tabs. And as the text says, you should use mlrt instead due to performance, since it is around 2x faster. The readme has a section for that. I may need to remove that so people will stop trying to use the deprecated esrgan inference.

I don't understand the second question and you should not mix questions in the same github issue.

**Comment by adhityanadooli** [comment]
I succeeded in getting it to render but when it did it only took two seconds and the output video was the same resolution and was a even smaller file size as the original, no errors popped up.

**Comment by styler00dollar** [comment]
I have no idea what you are even doing without seeing it.

**Comment by adhityanadooli** [comment]
No errors but it only rendered 2 seconds of the video
![image](https://user-images.githubusercontent.com/127269031/225498113-e16d44d2-9411-4719-a828-108f33511ce4.png)  What CMD said:  `root@7193be03f66c:/workspace/tensorrt# vspipe -c y4m inference.py - | ffmpeg -i pipe: example2B.mp4
ffmpeg version N-109993-g205117d87f Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.1 (GCC) 20230201
  configuration: --pkg-config-flags=--static --extra-cflags='-fopenmp -lcrypto -lz -ldl -static-libgcc' --extra-ldflags='-fopenmp -lcrypto -lz -ldl -static-libgcc' --extra-libs='-lstdc++ -lcrypto -lz -ldl -static-libgcc' --toolchain=hardened --disable-debug --disable-shared --disable-ffplay --enable-static --enable-gpl --enable-gray --enable-nonfree --enable-openssl --enable-iconv --enable-libxml2 --enable-libmp3lame --enable-libfdk-aac --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvpx --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libaom --enable-libvidstab --enable-libkvazaar --enable-libfreetype --enable-fontconfig --enable-libfribidi --enable-libass --enable-libsoxr --enable-libopenjpeg --enable-libdav1d --enable-librav1e --enable-libsrt --enable-libsvtav1 --enable-libdavs2 --enable-libxavs2 --enable-libvmaf --enable-cuda-nvcc --extra-cflags=-I/opt/cuda/include --extra-ldflags=-L/opt/cuda/lib64 --enable-vapoursynth --enable-libopenh264 --enable-optimizations --enable-cuda-llvm --enable-nvdec --enable-nvenc --enable-cuvid --enable-cuda --enable-pthreads --enable-runtime-cpudetect --enable-lto
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.101 / 60.  6.101
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Information: Generating grammar tables from /usr/lib/python3.10/lib2to3/Grammar.txt
Information: Generating grammar tables from /usr/lib/python3.10/lib2to3/PatternGrammar.txt
Warning: /usr/local/lib/python3.10/dist-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(

Input #0, yuv4mpegpipe, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p(progressive), 2160x3840, 23.98 fps, 23.98 tbr, 23.98 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[libx264 @ 0x5596898485c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5596898485c0] profile High, level 5.1, 4:2:0, 8-bit
[libx264 @ 0x5596898485c0] 264 - core 164 r3106 eaa68fa - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=23 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'example2B.mp4':
  Metadata:
    encoder         : Lavf60.4.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(progressive), 2160x3840, q=2-31, 23.98 fps, 24k tbn
    Metadata:
      encoder         : Lavc60.6.101 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  131 fps=1.1 q=-1.0 Lsize=    7064kB time=00:00:05.33 bitrate=10839.8kbits/s speed=0.0447x
video:7062kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.030242%
[libx264 @ 0x5596898485c0] frame I:6     Avg QP:14.84  size: 82301
[libx264 @ 0x5596898485c0] frame P:77    Avg QP:19.76  size: 62672
[libx264 @ 0x5596898485c0] frame B:48    Avg QP:18.58  size: 39819
[libx264 @ 0x5596898485c0] consecutive B-frames: 42.7% 21.4% 11.5% 24.4%
[libx264 @ 0x5596898485c0] mb I  I16..4: 48.1% 49.7%  2.2%
[libx264 @ 0x5596898485c0] mb P  I16..4: 15.8% 33.3%  0.7%  P16..4: 10.6%  1.9%  0.7%  0.0%  0.0%    skip:36.9%
[libx264 @ 0x5596898485c0] mb B  I16..4:  4.1%  3.4%  0.2%  B16..8: 15.2%  2.4%  0.3%  direct:14.4%  skip:60.0%  L0:46.7% L1:50.4% BI: 2.9%
[libx264 @ 0x5596898485c0] 8x8 transform intra:62.9% inter:87.3%
[libx264 @ 0x5596898485c0] coded y,uvDC,uvAC intra: 10.8% 44.5% 10.4% inter: 5.0% 21.6% 1.2%
[libx264 @ 0x5596898485c0] i16 v,h,dc,p: 38% 22%  4% 36%
[libx264 @ 0x5596898485c0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 44% 15% 32%  2%  2%  2%  2%  2%  1%
[libx264 @ 0x5596898485c0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 37% 21% 14%  4%  6%  6%  5%  4%  3%
[libx264 @ 0x5596898485c0] i8c dc,h,v,p: 53% 18% 15% 15%
[libx264 @ 0x5596898485c0] Weighted P-Frames: Y:1.3% UV:1.3%
[libx264 @ 0x5596898485c0] ref P L0: 65.2%  6.1% 17.5% 10.9%  0.3%
[libx264 @ 0x5596898485c0] ref B L0: 78.0% 18.5%  3.5%
[libx264 @ 0x5596898485c0] ref B L1: 95.5%  4.5%
[libx264 @ 0x5596898485c0] kb/s:10587.32 ``

**Comment by styler00dollar** [comment]
Sounds like out of memory. Try lower resolution. `mlrt` will give you less memory issues though.

**Comment by adhityanadooli** [comment]
I'm also confused about getting mlrt, the instructions are a little bit confusing, could you clarify it a little bit? I tried convering a ONNX file into an engine but got this :  `root@7193be03f66c:/workspace/tensorrt# trtexec --fp16 --onnx=realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
&&&& RUNNING TensorRT.trtexec [TensorRT v8503] # trtexec --fp16 --onnx=realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
[03/16/2023-03:41:14] [I] === Model Options ===
[03/16/2023-03:41:14] [I] Format: ONNX
[03/16/2023-03:41:14] [I] Model: realesr-animevideov3.onnx
[03/16/2023-03:41:14] [I] Output:
[03/16/2023-03:41:14] [I] === Build Options ===
[03/16/2023-03:41:14] [I] Max batch: explicit batch
[03/16/2023-03:41:14] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[03/16/2023-03:41:14] [I] minTiming: 1
[03/16/2023-03:41:14] [I] avgTiming: 8
[03/16/2023-03:41:14] [I] Precision: FP32+FP16
[03/16/2023-03:41:14] [I] LayerPrecisions:
[03/16/2023-03:41:14] [I] Calibration:
[03/16/2023-03:41:14] [I] Refit: Disabled
[03/16/2023-03:41:14] [I] Sparsity: Disabled
[03/16/2023-03:41:14] [I] Safe mode: Disabled
[03/16/2023-03:41:14] [I] DirectIO mode: Disabled
[03/16/2023-03:41:14] [I] Restricted mode: Disabled
[03/16/2023-03:41:14] [I] Build only: Enabled
[03/16/2023-03:41:14] [I] Save engine: animevideov3.engine
[03/16/2023-03:41:14] [I] Load engine:
[03/16/2023-03:41:14] [I] Profiling verbosity: 0
[03/16/2023-03:41:14] [I] Tactic sources: cublas [OFF], cublasLt [OFF], cudnn [ON],
[03/16/2023-03:41:14] [I] timingCacheMode: local
[03/16/2023-03:41:14] [I] timingCacheFile:
[03/16/2023-03:41:14] [I] Heuristic: Disabled
[03/16/2023-03:41:14] [I] Preview Features: Use default preview flags.
[03/16/2023-03:41:14] [I] Input(s)s format: fp32:CHW
[03/16/2023-03:41:14] [I] Output(s)s format: fp32:CHW
[03/16/2023-03:41:14] [I] Input build shape: input=1x3x8x8+1x3x720x1280+1x3x1080x1920
[03/16/2023-03:41:14] [I] Input calibration shapes: model
[03/16/2023-03:41:14] [I] === System Options ===
[03/16/2023-03:41:14] [I] Device: 0
[03/16/2023-03:41:14] [I] DLACore:
[03/16/2023-03:41:14] [I] Plugins:
[03/16/2023-03:41:14] [I] === Inference Options ===
[03/16/2023-03:41:14] [I] Batch: Explicit
[03/16/2023-03:41:14] [I] Input inference shape: input=1x3x720x1280
[03/16/2023-03:41:14] [I] Iterations: 10
[03/16/2023-03:41:14] [I] Duration: 3s (+ 200ms warm up)
[03/16/2023-03:41:14] [I] Sleep time: 0ms
[03/16/2023-03:41:14] [I] Idle time: 0ms
[03/16/2023-03:41:14] [I] Streams: 1
[03/16/2023-03:41:14] [I] ExposeDMA: Disabled
[03/16/2023-03:41:14] [I] Data transfers: Enabled
[03/16/2023-03:41:14] [I] Spin-wait: Disabled
[03/16/2023-03:41:14] [I] Multithreading: Disabled
[03/16/2023-03:41:14] [I] CUDA Graph: Disabled
[03/16/2023-03:41:14] [I] Separate profiling: Disabled
[03/16/2023-03:41:14] [I] Time Deserialize: Disabled
[03/16/2023-03:41:14] [I] Time Refit: Disabled
[03/16/2023-03:41:14] [I] NVTX verbosity: 0
[03/16/2023-03:41:14] [I] Persistent Cache Ratio: 0
[03/16/2023-03:41:14] [I] Inputs:
[03/16/2023-03:41:14] [I] === Reporting Options ===
[03/16/2023-03:41:14] [I] Verbose: Disabled
[03/16/2023-03:41:14] [I] Averages: 10 inferences
[03/16/2023-03:41:14] [I] Percentiles: 90,95,99
[03/16/2023-03:41:14] [I] Dump refittable layers:Disabled
[03/16/2023-03:41:14] [I] Dump output: Disabled
[03/16/2023-03:41:14] [I] Profile: Disabled
[03/16/2023-03:41:14] [I] Export timing to JSON file:
[03/16/2023-03:41:14] [I] Export output to JSON file:
[03/16/2023-03:41:14] [I] Export profile to JSON file:
[03/16/2023-03:41:14] [I]
[03/16/2023-03:41:14] [I] === Device Information ===
[03/16/2023-03:41:14] [I] Selected Device: NVIDIA GeForce RTX 3070
[03/16/2023-03:41:14] [I] Compute Capability: 8.6
[03/16/2023-03:41:14] [I] SMs: 46
[03/16/2023-03:41:14] [I] Compute Clock Rate: 1.725 GHz
[03/16/2023-03:41:14] [I] Device Global Memory: 8191 MiB
[03/16/2023-03:41:14] [I] Shared Memory per SM: 100 KiB
[03/16/2023-03:41:14] [I] Memory Bus Width: 256 bits (ECC disabled)
[03/16/2023-03:41:14] [I] Memory Clock Rate: 7.001 GHz
[03/16/2023-03:41:14] [I]
[03/16/2023-03:41:14] [I] TensorRT version: 8.5.3
[03/16/2023-03:41:14] [I] [TRT] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 26, GPU 1077 (MiB)
[03/16/2023-03:41:16] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +546, GPU +118, now: CPU 627, GPU 1195 (MiB)
[03/16/2023-03:41:16] [I] Start parsing network model
Could not open file realesr-animevideov3.onnx
Could not open file realesr-animevideov3.onnx
[03/16/2023-03:41:16] [E] [TRT] ModelImporter.cpp:688: Failed to parse ONNX model from file: realesr-animevideov3.onnx
[03/16/2023-03:41:16] [E] Failed to parse onnx file
[03/16/2023-03:41:16] [I] Finish parsing network model
[03/16/2023-03:41:16] [E] Parsing model failed
[03/16/2023-03:41:16] [E] Failed to create engine from model or file.
[03/16/2023-03:41:16] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8503] # trtexec --fp16 --onnx=realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
root@7193be03f66c:/workspace/tensorrt# trtexec --fp16 --onnx=realesr-realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=realesr-animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
&&&& RUNNING TensorRT.trtexec [TensorRT v8503] # trtexec --fp16 --onnx=realesr-realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=realesr-animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly
[03/16/2023-03:46:29] [I] === Model Options ===
[03/16/2023-03:46:29] [I] Format: ONNX
[03/16/2023-03:46:29] [I] Model: realesr-realesr-animevideov3.onnx
[03/16/2023-03:46:29] [I] Output:
[03/16/2023-03:46:29] [I] === Build Options ===
[03/16/2023-03:46:29] [I] Max batch: explicit batch
[03/16/2023-03:46:29] [I] Memory Pools: workspace: default, dlaSRAM: default, dlaLocalDRAM: default, dlaGlobalDRAM: default
[03/16/2023-03:46:29] [I] minTiming: 1
[03/16/2023-03:46:29] [I] avgTiming: 8
[03/16/2023-03:46:29] [I] Precision: FP32+FP16
[03/16/2023-03:46:29] [I] LayerPrecisions:
[03/16/2023-03:46:29] [I] Calibration:
[03/16/2023-03:46:29] [I] Refit: Disabled
[03/16/2023-03:46:29] [I] Sparsity: Disabled
[03/16/2023-03:46:29] [I] Safe mode: Disabled
[03/16/2023-03:46:29] [I] DirectIO mode: Disabled
[03/16/2023-03:46:29] [I] Restricted mode: Disabled
[03/16/2023-03:46:29] [I] Build only: Enabled
[03/16/2023-03:46:29] [I] Save engine: realesr-animevideov3.engine
[03/16/2023-03:46:29] [I] Load engine:
[03/16/2023-03:46:29] [I] Profiling verbosity: 0
[03/16/2023-03:46:29] [I] Tactic sources: cublas [OFF], cublasLt [OFF], cudnn [ON],
[03/16/2023-03:46:29] [I] timingCacheMode: local
[03/16/2023-03:46:29] [I] timingCacheFile:
[03/16/2023-03:46:29] [I] Heuristic: Disabled
[03/16/2023-03:46:29] [I] Preview Features: Use default preview flags.
[03/16/2023-03:46:29] [I] Input(s)s format: fp32:CHW
[03/16/2023-03:46:29] [I] Output(s)s format: fp32:CHW
[03/16/2023-03:46:29] [I] Input build shape: input=1x3x8x8+1x3x720x1280+1x3x1080x1920
[03/16/2023-03:46:29] [I] Input calibration shapes: model
[03/16/2023-03:46:29] [I] === System Options ===
[03/16/2023-03:46:29] [I] Device: 0
[03/16/2023-03:46:29] [I] DLACore:
[03/16/2023-03:46:29] [I] Plugins:
[03/16/2023-03:46:29] [I] === Inference Options ===
[03/16/2023-03:46:29] [I] Batch: Explicit
[03/16/2023-03:46:29] [I] Input inference shape: input=1x3x720x1280
[03/16/2023-03:46:29] [I] Iterations: 10
[03/16/2023-03:46:29] [I] Duration: 3s (+ 200ms warm up)
[03/16/2023-03:46:29] [I] Sleep time: 0ms
[03/16/2023-03:46:29] [I] Idle time: 0ms
[03/16/2023-03:46:29] [I] Streams: 1
[03/16/2023-03:46:29] [I] ExposeDMA: Disabled
[03/16/2023-03:46:29] [I] Data transfers: Enabled
[03/16/2023-03:46:29] [I] Spin-wait: Disabled
[03/16/2023-03:46:29] [I] Multithreading: Disabled
[03/16/2023-03:46:29] [I] CUDA Graph: Disabled
[03/16/2023-03:46:29] [I] Separate profiling: Disabled
[03/16/2023-03:46:29] [I] Time Deserialize: Disabled
[03/16/2023-03:46:29] [I] Time Refit: Disabled
[03/16/2023-03:46:29] [I] NVTX verbosity: 0
[03/16/2023-03:46:29] [I] Persistent Cache Ratio: 0
[03/16/2023-03:46:29] [I] Inputs:
[03/16/2023-03:46:29] [I] === Reporting Options ===
[03/16/2023-03:46:29] [I] Verbose: Disabled
[03/16/2023-03:46:29] [I] Averages: 10 inferences
[03/16/2023-03:46:29] [I] Percentiles: 90,95,99
[03/16/2023-03:46:29] [I] Dump refittable layers:Disabled
[03/16/2023-03:46:29] [I] Dump output: Disabled
[03/16/2023-03:46:29] [I] Profile: Disabled
[03/16/2023-03:46:29] [I] Export timing to JSON file:
[03/16/2023-03:46:29] [I] Export output to JSON file:
[03/16/2023-03:46:29] [I] Export profile to JSON file:
[03/16/2023-03:46:29] [I]
[03/16/2023-03:46:29] [I] === Device Information ===
[03/16/2023-03:46:29] [I] Selected Device: NVIDIA GeForce RTX 3070
[03/16/2023-03:46:29] [I] Compute Capability: 8.6
[03/16/2023-03:46:29] [I] SMs: 46
[03/16/2023-03:46:29] [I] Compute Clock Rate: 1.725 GHz
[03/16/2023-03:46:29] [I] Device Global Memory: 8191 MiB
[03/16/2023-03:46:29] [I] Shared Memory per SM: 100 KiB
[03/16/2023-03:46:29] [I] Memory Bus Width: 256 bits (ECC disabled)
[03/16/2023-03:46:29] [I] Memory Clock Rate: 7.001 GHz
[03/16/2023-03:46:29] [I]
[03/16/2023-03:46:29] [I] TensorRT version: 8.5.3
[03/16/2023-03:46:29] [I] [TRT] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 26, GPU 1077 (MiB)
[03/16/2023-03:46:30] [I] [TRT] [MemUsageChange] Init builder kernel library: CPU +546, GPU +118, now: CPU 627, GPU 1195 (MiB)
[03/16/2023-03:46:30] [I] Start parsing network model
Could not open file realesr-realesr-animevideov3.onnx
Could not open file realesr-realesr-animevideov3.onnx
[03/16/2023-03:46:30] [E] [TRT] ModelImporter.cpp:688: Failed to parse ONNX model from file: realesr-realesr-animevideov3.onnx
[03/16/2023-03:46:30] [E] Failed to parse onnx file
[03/16/2023-03:46:30] [I] Finish parsing network model
[03/16/2023-03:46:30] [E] Parsing model failed
[03/16/2023-03:46:30] [E] Failed to create engine from model or file.
[03/16/2023-03:46:30] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8503] # trtexec --fp16 --onnx=realesr-realesr-animevideov3.onnx --minShapes=input:1x3x8x8 --optShapes=input:1x3x720x1280 --maxShapes=input:1x3x1080x1920 --saveEngine=realesr-animevideov3.engine --tacticSources=+CUDNN,-CUBLAS,-CUBLAS_LT --buildOnly`

**Comment by styler00dollar** [comment]
It even says that it couldnt find the onnx file with given path. Read the errors more carefully.

**Comment by adhityanadooli** [comment]
I set it up but it keeps displaying errors when I try to render: Config ![image](https://user-images.githubusercontent.com/127269031/225780967-ab3fdae3-55f2-46d7-abeb-82acc174e40e.png)
Error: `1: [stdArchiveReader.cpp::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
Script evaluation failed:
Python exception: operator(): engine deserialization failed

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "inference.py", line 7, in <module>
    clip = inference_clip(video_path)
  File "/workspace/tensorrt/inference_config.py", line 163, in inference_clip
    clip = core.trt.Model(
  File "src/cython/vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: operator(): engine deserialization failed

pipe:: Invalid data found when processing input`

**Comment by mafiosnik777** [comment]
> I set it up but it keeps displaying errors when I try to render: Config ![image](https://user-images.githubusercontent.com/127269031/225780967-ab3fdae3-55f2-46d7-abeb-82acc174e40e.png) Error: `1: [stdArchiveReader.cpp::StdArchiveReader::32] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match) 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.) Script evaluation failed: Python exception: operator(): engine deserialization failed
> 
> Traceback (most recent call last): File "src/cython/vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate File "src/cython/vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate File "inference.py", line 7, in clip = inference_clip(video_path) File "/workspace/tensorrt/inference_config.py", line 163, in inference_clip clip = core.trt.Model( File "src/cython/vapoursynth.pyx", line 2847, in vapoursynth.Function.**call** vapoursynth.Error: operator(): engine deserialization failed
> 
> pipe:: Invalid data found when processing input`

You're feeding it the onnx and not the built engine file, hence engine serialization fails.

**Comment by adhityanadooli** [comment]
what path do i put in then?

**Comment by mafiosnik777** [comment]
> what path do i put in then?

The .engine you get from building with trtexec, not the .onnx.

**Comment by adhityanadooli** [comment]
when i was looking back at the output i didn’t see a .engine file path it gave me

**Comment by lightyfr** [comment]
yes, but while going through the output for that command it didn’t tell me the engine path, do i just put that model name.model? where are the .engine files stored?

**Comment by adhityanadooli** [comment]
I figured out how to use mlrt but it still wont render, docker destop keeps using absurd amounts of memory on idle.
![image](https://user-images.githubusercontent.com/127269031/226085239-689db772-00b9-4cc5-8211-2f705fe2554c.png)

**Comment by styler00dollar** [comment]
That seems to be Windows related since Arch Linux works fine. Sometimes a reboot can help. Closing issue since it is solved.

**Comment by adhityanadooli** [comment]
but it won’t render after countless restarts, how do i decrease the upscale from 4x to 2x with mlrt?

**Comment by styler00dollar** [comment]
Make new issues for new questions, and no, you can not change model scale since it is hardcoded into architecture. Look in https://github.com/styler00dollar/VSGAN-tensorrt-docker/issues/22 if you have out of vram.

**Comment by adhityanadooli** [comment]
I don’t get that error plus i have a 3070 with 16g of ram and a 5800x why is this happening? also when i render it only uses my cpu, is that supposed to happen?

**Comment by styler00dollar** [comment]
In terms of ai context this is low end hardware though and can easily result in out of memory. Without more information I cant help. Debug and get more information, open a new issue if once you got there and think it is another problem. One issue = One problem.
