### ISSUE TITLE
Error when using model based scene detect, Could i be pointed out where the problem is. [Help]

### ISSUE THREAD

**Issue by Anon1337Elite** [styler00dollar/VSGAN-tensorrt-docker#35]
When i use
  `  clip = scene_detect(clip, model_name="efficientnetv2_b0", thresh=0.98, fp16=False)`
I get the error below, how can i fix this ? Thanks.

```
2023-03-27 13:11:44.991887004 [W:onnxruntime:, session_state.cc:1030 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-03-27 13:11:44.991932404 [W:onnxruntime:, session_state.cc:1032 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Error: Failed to retrieve frame 1 with error:
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2941, in vapoursynth.publicFunction
  File "src/cython/vapoursynth.pyx", line 2943, in vapoursynth.publicFunction
  File "src/cython/vapoursynth.pyx", line 683, in vapoursynth.FuncData.__call__
  File "/workspace/tensorrt/src/scene_detect.py", line 316, in execute
    I0 = frame_to_tensor(clip.get_frame(n))
  File "/workspace/tensorrt/src/scene_detect.py", line 56, in frame_to_tensor
    return np.stack(
  File "<__array_function__ internals>", line 180, in stack
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

**Comment by styler00dollar** [comment]
Huh, I will check when I have time.

**Comment by Anon1337Elite** [comment]
> Huh, I will check when I have time.

i think it might been the model i was using weird issue. I gave up on it. Was using Anime6B model.

Dont have time to trouble shoot much.

**Comment by styler00dollar** [comment]
That scene detect is for interpolation though. Not for upscaling.

**Comment by Anon1337Elite** [comment]
> That scene detect is for interpolation though. Not for upscaling.

oh, lol. Yeah i was testing around i didn't much understand what was for what. Since that section has been kinda confusing for me. Srry.
