### ISSUE TITLE
cv.optflow has no attribute 'DualTVL10OpticalFlow_create' from eisai_arch.py

### ISSUE THREAD

**Issue by darkcristle** [styler00dollar/VSGAN-tensorrt-docker#53]
Hello!

I am currently trying to run [this](https://github.com/Sirosky/Upscale-Hub/wiki/%F0%9F%8C%9F-AniScale-2-&--AniScale-2-Refiner) compact model and am encountering a crash.   Trace below.    Some googling suggests you may be [missing a package](https://stackoverflow.com/questions/72364789/cv2-cant-find-an-attribiute-optflow-even-though-it-is-imported).

I also found [this](https://stackoverflow.com/questions/72364789/cv2-cant-find-an-attribiute-optflow-even-though-it-is-imported) suggesting that the calling has changed.  I edited the code to reflect both old and new methods and had the same error.   

`Traceback (most recent call last):                                                                                                
  File "src/cython/vapoursynth.pyx", line 3225, in vapoursynth._vpy_evaluate                                                      
  File "src/cython/vapoursynth.pyx", line 3226, in vapoursynth._vpy_evaluate                                                      
  File "inference_batch.py", line 5, in <module>                                                                                  
    from inference_config import inference_clip                                                                                   
  File "/workspace/tensorrt/inference_config.py", line 16, in <module>                                                            
    from src.eisai import EISAI                                                                                                   
  File "/workspace/tensorrt/src/eisai.py", line 4, in <module>                                                                    
    from .eisai_arch import SoftsplatLite, DTM, RAFT, interpolate                                                                 
  File "/workspace/tensorrt/src/eisai_arch.py", line 1586, in <module>                                                            
    _dtvl1_ = cv2.optflow.DualTVL1OpticalFlow_create()                                                                                                                                                        
AttributeError: module 'cv2.optflow' has no attribute 'DualTVL1OpticalFlow_create'  `

**Comment by styler00dollar** [comment]
I removed eisai due to broken dependencies like this one. I don't support it anymore. Reclone the github repository and download the latest docker. Looks like something is outdated on your side.

**Comment by darkcristle** [comment]
This fixed the issue.  Closing.
